DROP TABLE IF EXISTS gaihaku;
CREATE TABLE gaihaku (
    gaihaku_id  MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
    id          MEDIUMINT UNSIGNED NOT NULL,
    group_id    MEDIUMINT UNSIGNED,
    sub_date    DATETIME,
    class       VARCHAR(3),
    roomnum     VARCHAR(6),
    psCode1     VARCHAR(3),
    psCode2     VARCHAR(4),
    address     VARCHAR(128),
    last_name2  VARCHAR(50),
    first_name2 VARCHAR(50),
    tel         VARCHAR(16),
    s_day       DATETIME,
    s_time      CHAR(2),
    f_day       DATETIME,
    f_time      CHAR(2),
    reason      VARCHAR(4),
    riyuu       VARCHAR(700),
    state       DATETIME,
    auth        TINYINT,
    ryoukan     VARCHAR(101),
    teacher     VARCHAR(101),
    app         VARCHAR(3),
    app_date    DATETIME,
    comment     VARCHAR(700),   
    PRIMARY KEY(gaihaku_id)
);